### ISSUE TITLE
关于侧边栏文件折叠的问题

### ISSUE THREAD

**Issue by fannl** [dkheng/DogsChoice#2]
您好！
请问侧边栏文件的三角形符号及折叠功能代码是？
祝生活愉快。

**Comment by dkheng** [comment]
我并未对三角符号和折叠功能做定制，主题中应该没有相关的代码。
在theme.css文件400行左右有对文件树部分特征的定制，如下：
```css
#file-library-tree .file-tree-node {
    padding-left: .9em; /* 文件树每级缩进 */
    color: var(--control-text-color);
}

.file-tree-node .file-node-content:hover {
    background-color: var(--sidebar-btn-hover-color); /* 鼠标指向文件时的背景色 */
    cursor: pointer;
}
```
